---
- name: Configure an Ethernet connection with static IP
  hosts: all
  become: true
  tasks:
  - include_role:
      name: linux-system-roles.network

    vars:
      network_connections:
        - name: enp0s25
          type: ethernet
          autoconnect: yes
          ip:
            address:
              - 192.168.26.11/24
            gateway4: 192.168.26.1
            dns:
              - 192.168.26.1
          state: up
